module.exports = {
  projects: [
    '<rootDir>/apps/chuck-norris-front',
    '<rootDir>/apps/chuck-bff',
    '<rootDir>/libs/material',
    '<rootDir>/libs/material-lib',
    '<rootDir>/libs/interfaces',
    '<rootDir>/libs/all-categories',
    '<rootDir>/libs/modals',
    '<rootDir>/libs/routes',
    '<rootDir>/libs/pages',
    '<rootDir>/libs/other-imp',
    '<rootDir>/libs/selected-joke',
    '<rootDir>/libs/services',
    '<rootDir>/libs/services-chuck',
    '<rootDir>/libs/page1',
    '<rootDir>/libs/page2',
    '<rootDir>/libs/page2-lib',
    '<rootDir>/libs/page-lib',
    '<rootDir>/libs/page1-lib',
    '<rootDir>/libs/redux',
  ],
};
